### Run test remotely
# @timeout 120
POST http://77.234.215.138:34321/run
Content-Type: application/json

{
  "serviceName": "{{serviceName}}",
  "token": "{{token}}",
  "branch": "hw-5_2-etozheraf",
  "accounts": "acc-23",
  "ratePerSecond": 11,
  "testCount": 2200,
  "processingTimeMillis": 13000,
  "profile": "s_0.7_60"
}

### Stop running test to save credits
# @timeout 120
POST http://77.234.215.138:31234/test/stop/{{serviceName}}
