### Run test remotel
# @timeout 120
POST http://77.234.215.138:34321/run
Content-Type: application/json

{
  "serviceName": "{{serviceName}}",
  "token": "{{token}}",
  "accounts": "acc-12",
  "branch": "hw-9-new-Etozheraf",
  "ratePerSecond": 1000,
  "testCount": 200000,
  "processingTimeMillis": 50000
}

### Stop running test to save credits
# @timeout 120
POST http://77.234.215.138:31234/test/stop/{{serviceName}}
